task2/Controllers/ValidempController.cs
using Microsoft.AspNetCore.Mvc;
using task2.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using task2.Models;
using Microsoft.EntityFrameworkCore;


namespace task2.Controllers
{
    public class ValidempController : Controller
    {
        CompanyContext companyContext=new CompanyContext();
        
        public IActionResult Index()
        {
            List<employee> employees = companyContext.Employees.Include(d=>d.Department).ToList();
            return View(employees);
        }
        [HttpGet]
        public IActionResult Add() {

            EmployeeVM employeeVM = new EmployeeVM()
            {
                departments = new SelectList(companyContext.Departments, nameof(department.Id), nameof(department.Name))
            };
            return View(employeeVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(EmployeeVM emp) {
         if (ModelState.IsValid)
         {
                employee employee = new employee()
                {
                    fname = emp.fname,
                    lname = emp.lname,
                    address= emp.address,
                    password = emp.password,
                    dno = emp.dno,
                    bdate = emp.bdate,
                    salary = emp.salary,
                    Sex=emp.Sex
                };
                companyContext.Employees.Add(employee);
                companyContext.SaveChanges();
                return RedirectToAction(nameof(Index));
                
         }
            List<department>departments = companyContext.Departments.ToList(); 

            emp.departments=new SelectList(departments,nameof(department.Id),nameof(department.Name));

            return View(emp);
        }
    }
}

task2/Views/Validemp/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model EmployeeVM

<form asp-action="Add" asp-controller="Validemp" method="post">
 
    <div>
        <label asp-for="fname" class="form-label"></label>
        <input asp-for="fname" class="form-control" />
        <span asp-validation-for="fname" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="lname" class="form-label"></label>
        <input asp-for="lname" class="form-control" />
        <span asp-validation-for="lname" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="address" class="form-label"></label>
        <input asp-for="address" class="form-control" />
        <span asp-validation-for="address" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="salary" class="form-label"></label>
        <input asp-for="salary" class="form-control" />
        <span asp-validation-for="salary" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="bdate" class="form-label"></label>
        <input asp-for="bdate" class="form-control" />
        <span asp-validation-for="bdate" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="Sex" class="form-label"></label>
        <input asp-for="Sex" class="form-control" />
        <span asp-validation-for="Sex" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="password" class="form-label"></label>
        <input asp-for="password" class="form-control" />
        <span asp-validation-for="password" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="Confirmpassword" class="form-label"></label>
        <input asp-for="Confirmpassword" class="form-control" />
        <span asp-validation-for="Confirmpassword" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="dno" class="form-label"></label>
        <select asp-for="dno" asp-items="Model.departments" class="form-control">
        </select>
        <span asp-validation-for="dno" class="text-danger"></span>

    </div>
    <input type="submit" value="Add" />
</form>
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

task2/Views/Validemp/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int i = 0;
}
@model List<employee>
<a class="btn btn-outline-success" asp-action="Add" asp-controller="Validemp">Add</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Number</th>
            <th scope="col"> FristName</th>
            <th scope="col"> LastName</th>
            <th scope="col">Adress</th>
            <th scope="col">Salary</th>
            <th scope="col">department</th>

            
        </tr>
    </thead>
    <tbody>
        @foreach (employee emp in Model)
        {
            <tr>
                <th scope="row">@(++i)</th>
                <td>@emp.fname</td>
                <td>@emp.lname</td>
                <td>@emp.address</td>
                <td>@emp.salary</td>
                <td>@emp.Department.Name</td>
                
            </tr>
        }
    </tbody>
</table>