task2/Controllers/WorkController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using task2.Models;
using task2.ViewModels;

namespace task2.Controllers
{
    public class WorkController : Controller
    {
        CompanyContext companyContext;
        public WorkController()
        {

            companyContext = new CompanyContext();

        }
        public IActionResult Getall()
        {
            List<works_for> works_Fors = companyContext.works_Fors.Include(w => w.Project).Include(w => w.Employee).ToList();
            return View(works_Fors);
        }
        public IActionResult Edit(int id)
        {
            employee emp = companyContext.Employees.Where(p => p.Id == id).SingleOrDefault();
            List<project> project = companyContext.works_Fors.Include(w => w.Project).Where(w => w.essn == id).Select(p => p.Project).ToList();

            ViewBag.project = project;
          
            ViewBag.employee = emp;
            return View();
        }
        public IActionResult EditDB(works_for works)
        {
            companyContext.works_Fors.Update(works);
            companyContext.SaveChanges();
            return RedirectToAction("Getall");
        }

        public IActionResult editscript(int id, int ssn)
        {
            works_for hours = companyContext.works_Fors.Where(w => w.pnum == id && w.essn == ssn).FirstOrDefault();

            return PartialView("_editpartial", hours);

        }
    }
}

task2/Views/Work/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    SelectList list = new SelectList(ViewBag.project, "Id", "pname");
    employee emp = ViewBag.employee;
}
@model works_for
<h1>Edit Houres</h1>


<form asp-action="EditDB" asp-controller="Work">
    <input hidden asp-for="essn" value="@ViewBag.employee.Id" />
    <div class="form-group">
        <label class="control-label">first name</label>
        <input value="@ViewBag.employee.fname" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="pnum" class="control-label">Project</label>
        <select asp-for="pnum" asp-items="list" class="form-select" onchange="gethour(this.value,'@emp.Id')"></select>
    </div>
    <div class="form-group" id="houres">
    </div>
    <button class="btn btn-outline-success" type="submit">Edit</button>
</form>
@section scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/edit.js"></script>
}

task2/Views/Work/Getall.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_ EmployeeLayout";
    int i = 1;
}
@* @model works_for *@
<h1> Works projectes </h1>

<style>

    h1 {
        color: darkgreen;
        text-align: center;
        margin-top: 100px
    }

    .rin_body {
        margin-top: 100px;
        margin-bottom: 100px;
    }

    p {
        text-align: center;
    }
    text{
        color:red
    }
</style>
<div class="rin_body">

    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">Number</th>
                <th scope="col">Employee</th>
                <th scope="col">Project </th>
                <th scope="col">Hours </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@(i++)</th>

                    <td>
                       @if (item.Employee!= null)
                        {
                            @item.Employee.fname
                            ;
                        }
                        else
                        {
                            @Html.Raw("Null")
                        } 

                    </td> 
                    <td>
                        @if (item.Project != null)
                        {
                            @item.Project.pname
                            ;
                        }
                        else
                        {
                            @Html.Raw("Null")
                        }

                    </td>
                    <td>
                       
                        
                         <div style="color:@(item.houres>5?"green":"red");">
                            @item.houres
                         </div>
                        

                    </td>
                


                    <td><a asp-action="Edit" asp-controller="work" asp-route-id="@item.essn" class="btn btn-outline-success">Edit</a> </td>


                    


                </tr>
            }
        </tbody>
    </table>
</div>